android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC
kotlin.incremental=true
org.gradle.parallel=true
org.gradle.caching=true
